# Generated by Django 3.2.5 on 2021-07-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Featured_Image',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
