# Generated by Django 3.2.5 on 2021-07-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210723_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='Featured_Image',
            new_name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='page',
            name='Featured_Image',
        ),
        migrations.AddField(
            model_name='page',
            name='thumbnail',
            field=models.ImageField(default=None, upload_to='images'),
            preserve_default=False,
        ),
    ]
