# Generated by Django 3.2.5 on 2021-07-24 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210724_0335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='categery',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['-pk']},
        ),
    ]
