# Generated by Django 3.2.5 on 2021-07-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_comment_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seo_Setup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SiteName', models.CharField(default='Hello World', max_length=50)),
                ('SiteDecs', models.TextField(default=None)),
                ('SiteMetaDecs', models.TextField(default=None)),
                ('Favicon', models.ImageField(default='/static/favicon/default.jpg', upload_to='static/favicon')),
                ('SiteKeywords', models.TextField(default=None)),
                ('MainMenu', models.ManyToManyField(to='home.Categery')),
            ],
        ),
    ]
