# Generated by Django 3.2.5 on 2021-07-27 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_seo_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='keywords',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_decs',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
