# Generated by Django 3.2.5 on 2021-07-27 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210726_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='keywords',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_decs',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
